In [5]:
import numpy as np
import copy, math
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)  # reduced display precision on numpy arrays

In [7]:
import numpy as np

X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

# Each row of the matrix represents one training example 
#when we have 'm' training examples, we will have 'm' rows
#when we have 'n' features per example, we will have 'n' columns

#that is a matrix of dimensions of (m, n)

print(f"X_train:{X_train}     X shape: {X_train.shape},     X Type:{type(X_train)}")
print(f"Y_train:{y_train}     Y shape: {y_train.shape},     X Type:{type(y_train)}")

X_train:[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]     X shape: (3, 4),     X Type:<class 'numpy.ndarray'>
Y_train:[460 232 178]     Y shape: (3,),     X Type:<class 'numpy.ndarray'>


In [8]:
b_init = 785.181136
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type:{type(b_init)}")

w_init shape: (4,), b_init type:<class 'float'>


In [15]:
#Single Prediction (y hat) element by element

#still a loop

x = X_train[0]
def predict_single_loop(x, w, b): 

    n = x.shape[0]
    p = 0
    for i in range(n):
        p_i = x[i] * w[i]  
        p = p + p_i         
    p = p + b                
    return p

predict_single_loop(x, w_init, b_init)

np.float64(459.9999968200001)

In [16]:
#Single Prediction (y hat) vector

# y hat = w1x1 + w2x2+ ...+ b

#now vectorized

x = X_train[0]
def predict_single_loop(x, w, b): 
    p = np.dot(x, w) + b              
    return p

predict_single_loop(x, w_init, b_init)

np.float64(459.9999968200001)

In [6]:
#Calculating the Cost (J(w,b))

import numpy as np

X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

b_init = 785.181136
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])


def compute_cost(X, y, w, b):
    m = X.shape[0]
    cost = 0.0
    for i in range(m):
        cost = cost + ((np.dot (X[i], w)+b - y[i])**2)/(2*m)
    return cost

print(compute_cost(X_train, y_train, w_init, b_init))

3.215566700216876e-12


In [14]:
#Compute Gradient with Multiple Variables

def compute_gradient(X, y, w, b):

    """
    Inputs:
X: Training data, shape (m,n), where
    m = number of training examples
    n = number of features
y: Target values (length m)
w: Current weight vector (length n)
b: Current bias (scalar)
"""
    
    m,n = X.shape
    dj_dw = np.zeros((n,))
    dj_db = 0

    for i in range (m): 
        err = (np.dot(X[i], w) + b) -y[i]   #(y^ - y)
        for j in range (n):
            dj_dw[j] = dj_dw[j] + err * X[i,j] #adds (ŷ - y) * x_j
        dj_db = dj_db + err  
    dj_dw = dj_dw/m
    dj_db = dj_db/m

    return dj_db, dj_dw

tmp_dj_db, tmp_dj_dw = compute_gradient(X_train, y_train, w_init, b_init)
print(f"dj_db at initial w,b: {tmp_dj_db}")
print(f"dj_dw at initial w,b: \n{tmp_dj_dw}")


dj_db at initial w,b: -2.4733333627106426e-06
dj_dw at initial w,b: 
[-3.89124001e-03 -8.93666667e-06 -3.28333340e-06 -1.01216668e-04]


In [15]:
def gradient_descent(X, y, w_in, b_in, cost_function, gradient_function, alpha, num_iters): 
    """
    Performs batch gradient descent to learn w and b. Updates w and b by taking 
    num_iters gradient steps with learning rate alpha
    
    Args:
      X (ndarray (m,n))   : Data, m examples with n features
      y (ndarray (m,))    : target values
      w_in (ndarray (n,)) : initial model parameters  
      b_in (scalar)       : initial model parameter
      cost_function       : function to compute cost
      gradient_function   : function to compute the gradient
      alpha (float)       : Learning rate
      num_iters (int)     : number of iterations to run gradient descent
      
    Returns:
      w (ndarray (n,)) : Updated values of parameters 
      b (scalar)       : Updated value of parameter 
      """
    
    # An array to store cost J and w's at each iteration primarily for graphing later
    J_history = []
    w = copy.deepcopy(w_in)  #avoid modifying global w within function
    b = b_in
    
    for i in range(num_iters):

        # Calculate the gradient and update the parameters
        dj_db,dj_dw = gradient_function(X, y, w, b)   ##None

        # Update Parameters using w, b, alpha and gradient
        w = w - alpha * dj_dw               ##None
        b = b - alpha * dj_db               ##None
      
        # Save cost J at each iteration
        if i<100000:      # prevent resource exhaustion 
            J_history.append( cost_function(X, y, w, b))

        # Print cost every at intervals 10 times or as many iterations if < 10
        if i% math.ceil(num_iters / 10) == 0:
            print(f"Iteration {i:4d}: Cost {J_history[-1]:8.2f}   ")
        
    return w, b, J_history #return final w,b and J history for graphing


# initialize parameters
initial_w = np.zeros_like(w_init)
initial_b = 0.
# some gradient descent settings
iterations = 1000
alpha = 5.0e-7
# run gradient descent 
w_final, b_final, J_hist = gradient_descent(X_train, y_train, initial_w, initial_b,
                                                    compute_cost, compute_gradient, 
                                                    alpha, iterations)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

NameError: name 'copy' is not defined